"""Tell the user's real input apart from Elaina's own (Phase 4F).

Elaina and the person share one mouse and one keyboard.  Before she moves
the pointer she has to know whether the machine is currently in use, and
while she is working she has to notice the moment it is taken back.  Both
questions reduce to one: *did that input come from a person or from us?*

``GetLastInputInfo`` cannot answer it.  Measured directly: a ``SendInput``
call from this process updates the system's last-input time exactly like a
keystroke, so a driver polling it detects itself and concludes the user is
always busy.

Low-level hooks can answer it.  Windows sets ``LLMHF_INJECTED`` /
``LLKHF_INJECTED`` on synthetic events, and measurement confirmed the
separation is clean: 26 mouse and 6 keyboard events generated by
``CursorDriver`` all arrived flagged, and none was counted as real.  So
*unflagged input is the person*, and that is the whole basis of the
mid-run emergency-stop behaviour.

Two consequences shape the implementation:

* **The callback runs inside the system input path.**  Every mouse move on
  the machine passes through it, so it does nothing but record a timestamp
  and hand on to the next hook.  Anything slower would make the whole
  desktop feel laggy.
* **Hooks can be refused.**  Some security software blocks them.  This
  reports that plainly through :attr:`available` rather than returning
  "user is idle" forever, so the layer above can fall back to pointer-drift
  detection and say that it is doing so.

Two later measurements on this machine, kept because they bound what the
hook can and cannot see:

* ``SendInput`` moves arrive flagged, 20 of 20, and an idle machine
  produces no callbacks at all.  So a recorded unflagged event is a real
  event; the counters are not background noise.
* ``SetCursorPos`` produces **no low-level hook events whatsoever**, while
  still moving the pointer (measured: 946,499 -> 740,400, zero callbacks).
  Anything that moves the cursor that way -- pywinauto's ``set_focus``
  does, to (-10000, 500) -- is invisible here and shows up only as pointer
  drift.  That is why drift is a separate branch that must not claim to
  know who moved anything.

What the hook records is therefore evidence, and :class:`RealEvent` keeps
enough of it to argue with.
"""

from __future__ import annotations

import ctypes
import ctypes.wintypes as wintypes
import threading
import time
from collections import deque
from dataclasses import dataclass

_WH_KEYBOARD_LL = 13
_WH_MOUSE_LL = 14
_LLMHF_INJECTED = 0x00000001
# Set when the injector was a lower-integrity process. Recorded separately:
# it is the one flag that distinguishes "something else automated this" from
# "a person did it", and a cancellation that blames the person should have
# to show it is clear.
_LLMHF_LOWER_IL_INJECTED = 0x00000002
_LLKHF_INJECTED = 0x00000010
_LLKHF_LOWER_IL_INJECTED = 0x00000020

# Mouse messages, so a recorded event can say what it actually was rather
# than only that "the mouse" did something.
_MOUSE_MESSAGES = {
    0x0200: "move", 0x0201: "left_down", 0x0202: "left_up",
    0x0203: "left_double", 0x0204: "right_down", 0x0205: "right_up",
    0x0206: "right_double", 0x0207: "middle_down", 0x0208: "middle_up",
    0x0209: "middle_double", 0x020A: "wheel", 0x020E: "hwheel",
    0x020B: "x_down", 0x020C: "x_up", 0x020D: "x_double",
}
_BUTTON_DOWN_MESSAGES = {0x0201: 1, 0x0204: 2, 0x0207: 4, 0x020B: 8}
_BUTTON_UP_MESSAGES = {0x0202: 1, 0x0205: 2, 0x0208: 4, 0x020C: 8}

# How many recent unflagged events to keep for diagnosis. Small: this is
# evidence for the last cancellation, not a log.
_EVIDENCE_DEPTH = 32

# How long the message pump waits between drains. Low-level hooks are
# delivered to the installing thread's queue, so it only has to stay
# responsive, not spin.
_PUMP_INTERVAL_SECONDS = 0.01
# How long after one of Elaina's own injected events an unflagged event is
# still assumed to be that same event arriving without its flag.
SELF_ECHO_SECONDS = 0.35
_HOOK_INSTALL_TIMEOUT_SECONDS = 2.0

try:
    _user32 = ctypes.windll.user32
except Exception:  # pragma: no cover - non-Windows host
    _user32 = None


def _tick_count() -> int:
    """The same clock a hook event stamps itself with, so they compare."""
    if _user32 is None:
        return int(time.monotonic() * 1000)
    try:
        return int(ctypes.windll.kernel32.GetTickCount())
    except Exception:  # pragma: no cover - platform failure
        return int(time.monotonic() * 1000)


def _signed_word(value: int) -> int:
    """mouseData carries a signed wheel delta in its high word."""
    value &= 0xFFFF
    return value - 0x10000 if value >= 0x8000 else value


class _MSLLHOOKSTRUCT(ctypes.Structure):
    _fields_ = [
        ("pt", wintypes.POINT), ("mouseData", wintypes.DWORD),
        ("flags", wintypes.DWORD), ("time", wintypes.DWORD),
        ("dwExtraInfo", ctypes.POINTER(wintypes.ULONG)),
    ]


class _KBDLLHOOKSTRUCT(ctypes.Structure):
    _fields_ = [
        ("vkCode", wintypes.DWORD), ("scanCode", wintypes.DWORD),
        ("flags", wintypes.DWORD), ("time", wintypes.DWORD),
        ("dwExtraInfo", ctypes.POINTER(wintypes.ULONG)),
    ]


@dataclass(frozen=True)
class RealEvent:
    """One unflagged input event, with enough detail to argue about it.

    Cancelling a browser action and telling somebody they moved the mouse
    is a claim about them. This is the evidence for it, captured at the
    moment the hook saw the event, because none of it can be recovered
    afterwards.

    ``at_tick`` is the event's own Windows timestamp and ``seen_tick`` is
    when this process got round to it. Low-level hooks are delivered to the
    installing thread's message queue, so those are not the same number,
    and the gap decides whether an event that looks like it happened during
    an action actually happened before it.
    """

    kind: str            # "mouse" | "key"
    what: str            # "move", "left_down", "wheel", "key_down", ...
    x: int
    y: int
    extra: int           # mouseData: wheel delta or which X button
    flags: int           # raw hook flags, injected bits included
    lower_il: bool       # injected by a lower-integrity process
    at_tick: int         # the event's own time, GetTickCount ms
    seen_tick: int       # when this process processed it
    at: float            # processing time on the watcher's clock
    buttons_down: int    # physical buttons held, from the message stream
    since_self_ms: float | None    # ms since Elaina last injected
    self_point: tuple[int, int] | None  # where she injected it
    action: str          # the action id in flight, if any

    @property
    def queue_lag_ms(self) -> int:
        """How late this process saw an event that had already happened."""
        return max(0, self.seen_tick - self.at_tick)

    @property
    def distance_from_self(self) -> int | None:
        """How far this event is from where Elaina last put the pointer."""
        if self.self_point is None or self.kind != "mouse":
            return None
        return max(
            abs(self.x - self.self_point[0]), abs(self.y - self.self_point[1]),
        )

    def describe(self) -> str:
        since = (
            "never" if self.since_self_ms is None
            else f"{self.since_self_ms:.0f}ms"
        )
        distance = self.distance_from_self
        return (
            f"{self.kind}/{self.what} at=({self.x},{self.y}) "
            f"flags=0x{self.flags:02x} lower_il={self.lower_il} "
            f"buttons=0x{self.buttons_down:x} extra={self.extra} "
            f"queue_lag={self.queue_lag_ms}ms "
            f"since_injection={since} "
            f"injected_at={self.self_point} "
            f"distance_from_injection={distance} "
            f"action={self.action or 'none'}"
        )


# LRESULT is LONG_PTR; declaring it (and the argtypes) matters on 64-bit --
# without it ctypes truncates the LPARAM and CallNextHookEx raises inside
# the hook callback, which silently breaks the whole chain.
_HOOKPROC = ctypes.WINFUNCTYPE(
    wintypes.LPARAM, ctypes.c_int, wintypes.WPARAM, wintypes.LPARAM,
)
if _user32 is not None:  # pragma: no branch - trivial guard
    _user32.CallNextHookEx.argtypes = [
        wintypes.HHOOK, ctypes.c_int, wintypes.WPARAM, wintypes.LPARAM,
    ]
    _user32.CallNextHookEx.restype = wintypes.LPARAM
    _user32.SetWindowsHookExW.argtypes = [
        ctypes.c_int, _HOOKPROC, wintypes.HINSTANCE, wintypes.DWORD,
    ]
    _user32.SetWindowsHookExW.restype = wintypes.HHOOK


class InputWatcher:
    """Watch for input the *user* generates, ignoring Elaina's own.

    One instance is meant to be created for the process and shared. Start it
    once; it runs a daemon thread and stops with the app.
    """

    def __init__(self, *, clock=None) -> None:
        self._clock = clock or time.monotonic
        self._lock = threading.Lock()
        self._last_real_input: float | None = None
        self._real_mouse_events = 0
        self._real_key_events = 0
        self._injected_events = 0
        self._self_echo_events = 0
        self._last_self_input: float | None = None
        self._last_self_point: tuple[int, int] | None = None
        self._last_real_kind = ""
        self._last_real: RealEvent | None = None
        self._recent_real: deque[RealEvent] = deque(maxlen=_EVIDENCE_DEPTH)
        self._buttons_down = 0
        self._action = ""
        self._action_started = 0.0
        self._action_counts = {"real_mouse": 0, "real_key": 0,
                               "injected": 0, "self_echo": 0}
        self._thread: threading.Thread | None = None
        self._stop = threading.Event()
        self._installed = threading.Event()
        self._install_error = ""
        # Kept alive deliberately: Windows holds a raw pointer to these
        # trampolines, and letting them be collected crashes the hook chain.
        self._mouse_proc = None
        self._key_proc = None

    # ------------------------------------------------------------------
    # lifecycle

    def start(self) -> bool:
        """Install the hooks. Returns whether watching is actually active."""
        if _user32 is None:
            self._install_error = "Windows input hooks are not available here."
            return False
        if self._thread is not None and self._thread.is_alive():
            return self._installed.is_set()
        self._stop.clear()
        self._installed.clear()
        self._thread = threading.Thread(
            target=self._pump, name="elaina-input-watcher", daemon=True,
        )
        self._thread.start()
        self._installed.wait(_HOOK_INSTALL_TIMEOUT_SECONDS)
        return self._installed.is_set()

    def stop(self) -> None:
        self._stop.set()
        thread = self._thread
        if thread is not None:
            thread.join(timeout=1.0)
        self._thread = None

    @property
    def available(self) -> bool:
        """True when real input is genuinely being observed."""
        return self._installed.is_set()

    @property
    def unavailable_reason(self) -> str:
        return self._install_error

    # ------------------------------------------------------------------
    # hook plumbing

    def _pump(self) -> None:
        mouse_hook = key_hook = None
        try:
            self._mouse_proc = _HOOKPROC(self._on_mouse)
            self._key_proc = _HOOKPROC(self._on_key)
            mouse_hook = _user32.SetWindowsHookExW(
                _WH_MOUSE_LL, self._mouse_proc, None, 0,
            )
            key_hook = _user32.SetWindowsHookExW(
                _WH_KEYBOARD_LL, self._key_proc, None, 0,
            )
            if not mouse_hook or not key_hook:
                self._install_error = (
                    "Windows refused to install the input hooks, so I cannot "
                    "reliably tell your input apart from mine."
                )
                return
            self._installed.set()
            message = wintypes.MSG()
            while not self._stop.is_set():
                while _user32.PeekMessageW(
                    ctypes.byref(message), None, 0, 0, 1,
                ):
                    _user32.TranslateMessage(ctypes.byref(message))
                    _user32.DispatchMessageW(ctypes.byref(message))
                time.sleep(_PUMP_INTERVAL_SECONDS)
        except Exception as error:  # pragma: no cover - platform failure
            self._install_error = (
                f"Input watching failed to start ({type(error).__name__})."
            )
        finally:
            self._installed.clear()
            for hook in (mouse_hook, key_hook):
                if hook:
                    try:
                        _user32.UnhookWindowsHookEx(hook)
                    except Exception:
                        pass

    def note_self_input(self, point: tuple[int, int] | None = None) -> None:
        """Elaina is about to inject something. Remember when.

        The injected flag is the primary test and it is the right one --
        measured, 26 mouse and 6 keyboard events from CursorDriver all
        arrived flagged. But "measured on one machine" is not "true on
        every machine": a pointing-device driver, an overlay, or a remote
        session can pass one of our own events through unflagged, and the
        cost of believing it is that Elaina cancels her own work and
        blames the person for it.

        So an unflagged event arriving in the moment after we injected one
        is treated as ours. It costs a fraction of a second of
        responsiveness to a real interruption, which is the cheaper of the
        two mistakes by a wide margin.
        """
        with self._lock:
            self._last_self_input = self._clock()
            if point is not None:
                self._last_self_point = (int(point[0]), int(point[1]))

    def begin_action(self, action: str) -> None:
        """Name the action now in flight and scope the counters to it.

        The lifetime tallies are the wrong number to reason about. Four
        thousand mouse events across a session says nothing; four thousand
        during one click says the hook is seeing something it should not.
        """
        with self._lock:
            self._action = str(action or "")
            self._action_started = self._clock()
            self._action_counts = {"real_mouse": 0, "real_key": 0,
                                   "injected": 0, "self_echo": 0}

    def end_action(self) -> None:
        with self._lock:
            self._action = ""

    def _record_real(self, *, mouse: bool, what: str = "", x: int = 0, y: int = 0,
                     extra: int = 0, flags: int = 0, lower_il: bool = False,
                     at_tick: int = 0) -> None:
        now = self._clock()
        seen_tick = _tick_count()
        with self._lock:
            since_self = (
                None if self._last_self_input is None
                else (now - self._last_self_input) * 1000.0
            )
            recent_self = (
                since_self is not None
                and since_self < SELF_ECHO_SECONDS * 1000.0
            )
            if recent_self:
                self._self_echo_events += 1
                self._action_counts["self_echo"] += 1
                return
            kind = "mouse" if mouse else "key"
            event = RealEvent(
                kind=kind, what=what or kind, x=x, y=y,
                extra=extra, flags=flags, lower_il=lower_il,
                at_tick=at_tick, seen_tick=seen_tick, at=now,
                buttons_down=self._buttons_down, since_self_ms=since_self,
                self_point=self._last_self_point, action=self._action,
            )
            self._last_real_input = now
            self._last_real_kind = kind
            self._last_real = event
            self._recent_real.append(event)
            if mouse:
                self._real_mouse_events += 1
                self._action_counts["real_mouse"] += 1
            else:
                self._real_key_events += 1
                self._action_counts["real_key"] += 1

    def _on_mouse(self, code, wparam, lparam):
        # Deliberately minimal: this runs for every mouse event on the
        # machine, ahead of the application that will receive it. Reading
        # the struct's own fields is free -- it is already mapped -- so the
        # cost here is the same as it was before it recorded anything.
        if code >= 0:
            try:
                data = ctypes.cast(
                    lparam, ctypes.POINTER(_MSLLHOOKSTRUCT),
                ).contents
                message = int(wparam)
                # Physical button state comes from the message stream
                # rather than a syscall per event: a move while a button is
                # held is a drag, and a person is doing it.
                if message in _BUTTON_DOWN_MESSAGES:
                    self._buttons_down |= _BUTTON_DOWN_MESSAGES[message]
                elif message in _BUTTON_UP_MESSAGES:
                    self._buttons_down &= ~_BUTTON_UP_MESSAGES[message]
                if data.flags & _LLMHF_INJECTED:
                    self._injected_events += 1
                    self._action_counts["injected"] += 1
                else:
                    self._record_real(
                        mouse=True,
                        what=_MOUSE_MESSAGES.get(message, f"0x{message:04x}"),
                        x=int(data.pt.x), y=int(data.pt.y),
                        extra=_signed_word(int(data.mouseData) >> 16),
                        flags=int(data.flags),
                        lower_il=bool(data.flags & _LLMHF_LOWER_IL_INJECTED),
                        at_tick=int(data.time),
                    )
            except Exception:
                pass
        return _user32.CallNextHookEx(None, code, wparam, lparam)

    def _on_key(self, code, wparam, lparam):
        if code >= 0:
            try:
                data = ctypes.cast(
                    lparam, ctypes.POINTER(_KBDLLHOOKSTRUCT),
                ).contents
                if data.flags & _LLKHF_INJECTED:
                    self._injected_events += 1
                    self._action_counts["injected"] += 1
                else:
                    self._record_real(
                        mouse=False,
                        what=f"vk_0x{int(data.vkCode):02x}",
                        flags=int(data.flags),
                        lower_il=bool(data.flags & _LLKHF_LOWER_IL_INJECTED),
                        at_tick=int(data.time),
                    )
            except Exception:
                pass
        return _user32.CallNextHookEx(None, code, wparam, lparam)

    # ------------------------------------------------------------------
    # queries

    def seconds_since_user_input(self) -> float | None:
        """How long since the person last touched the machine.

        ``None`` means "no real input has been seen" -- which is also what a
        watcher that never installed reports, so callers must check
        :attr:`available` rather than reading None as "the user is idle".
        """
        with self._lock:
            last = self._last_real_input
        if last is None:
            return None
        return max(0.0, self._clock() - last)

    def user_active_within(self, seconds: float) -> bool:
        """True when the person used the machine in the last ``seconds``."""
        elapsed = self.seconds_since_user_input()
        if elapsed is None:
            return False
        return elapsed <= max(0.0, float(seconds))

    def mark(self) -> float:
        """A checkpoint value for :meth:`user_input_since`."""
        return self._clock()

    def user_input_since(self, marker: float) -> bool:
        """Whether the person has provided input since a checkpoint.

        This is the mid-run interruption test: take a mark before an action,
        ask afterwards. Unlike pointer-position comparison it also catches
        typing, which never moves the mouse at all.
        """
        with self._lock:
            last = self._last_real_input
        return last is not None and last > marker

    def counters(self) -> dict[str, int]:
        """Event tallies, for diagnostics and the live checks."""
        with self._lock:
            return {
                "real_mouse": self._real_mouse_events,
                "real_key": self._real_key_events,
                "injected": self._injected_events,
                "self_echo": self._self_echo_events,
            }

    def last_real_event(self) -> tuple[str, float | None]:
        """What the last unflagged event was, and when. For the log.

        A cancellation that says "you moved the mouse" has to be able to
        show the event it is talking about.
        """
        with self._lock:
            return self._last_real_kind, self._last_real_input

    def last_real_detail(self) -> RealEvent | None:
        """The whole record of the last unflagged event."""
        with self._lock:
            return self._last_real

    def real_events_since(self, marker: float) -> tuple[RealEvent, ...]:
        """Every recorded unflagged event after a checkpoint.

        A run that cancels six times over one event and a run interrupted
        six times look identical from a single timestamp. They do not look
        alike here.
        """
        with self._lock:
            return tuple(e for e in self._recent_real if e.at > marker)

    def action_counters(self) -> dict[str, int]:
        """Tallies since :meth:`begin_action`, and how long that has been.

        The lifetime numbers cannot answer "is this traffic normal?"
        because they include every minute the person spent using their own
        machine. These only count what happened while Elaina was working.
        """
        with self._lock:
            counts = dict(self._action_counts)
            counts["elapsed_ms"] = int(
                (self._clock() - self._action_started) * 1000
            ) if self._action_started else 0
            return counts

    def evidence_since(self, marker: float) -> str:
        """One line naming what the hook actually saw, for the log."""
        events = self.real_events_since(marker)
        counts = self.action_counters()
        if not events:
            last = self.last_real_detail()
            seen = f"last_recorded=({last.describe()})" if last else "none recorded"
            return f"no events after mark; {seen}; action_counters={counts}"
        first = events[0]
        return (
            f"{len(events)} unflagged event(s) after mark; "
            f"first=({first.describe()}); "
            f"kinds={sorted({e.what for e in events})}; "
            f"action_counters={counts}"
        )
