"""Tell the user's real input apart from Elaina's own (Phase 4F).

Elaina and the person share one mouse and one keyboard.  Before she moves
the pointer she has to know whether the machine is currently in use, and
while she is working she has to notice the moment it is taken back.  Both
questions reduce to one: *did that input come from a person or from us?*

``GetLastInputInfo`` cannot answer it.  Measured directly: a ``SendInput``
call from this process updates the system's last-input time exactly like a
keystroke, so a driver polling it detects itself and concludes the user is
always busy.

Low-level hooks can answer it.  Windows sets ``LLMHF_INJECTED`` /
``LLKHF_INJECTED`` on synthetic events, and measurement confirmed the
separation is clean: 26 mouse and 6 keyboard events generated by
``CursorDriver`` all arrived flagged, and none was counted as real.  So
*unflagged input is the person*, and that is the whole basis of the
mid-run emergency-stop behaviour.

Two consequences shape the implementation:

* **The callback runs inside the system input path.**  Every mouse move on
  the machine passes through it, so it does nothing but record a timestamp
  and hand on to the next hook.  Anything slower would make the whole
  desktop feel laggy.
* **Hooks can be refused.**  Some security software blocks them.  This
  reports that plainly through :attr:`available` rather than returning
  "user is idle" forever, so the layer above can fall back to pointer-drift
  detection and say that it is doing so.
"""

from __future__ import annotations

import ctypes
import ctypes.wintypes as wintypes
import threading
import time

_WH_KEYBOARD_LL = 13
_WH_MOUSE_LL = 14
_LLMHF_INJECTED = 0x00000001
_LLKHF_INJECTED = 0x00000010

# How long the message pump waits between drains. Low-level hooks are
# delivered to the installing thread's queue, so it only has to stay
# responsive, not spin.
_PUMP_INTERVAL_SECONDS = 0.01
# How long after one of Elaina's own injected events an unflagged event is
# still assumed to be that same event arriving without its flag.
SELF_ECHO_SECONDS = 0.35
_HOOK_INSTALL_TIMEOUT_SECONDS = 2.0

try:
    _user32 = ctypes.windll.user32
except Exception:  # pragma: no cover - non-Windows host
    _user32 = None


class _MSLLHOOKSTRUCT(ctypes.Structure):
    _fields_ = [
        ("pt", wintypes.POINT), ("mouseData", wintypes.DWORD),
        ("flags", wintypes.DWORD), ("time", wintypes.DWORD),
        ("dwExtraInfo", ctypes.POINTER(wintypes.ULONG)),
    ]


class _KBDLLHOOKSTRUCT(ctypes.Structure):
    _fields_ = [
        ("vkCode", wintypes.DWORD), ("scanCode", wintypes.DWORD),
        ("flags", wintypes.DWORD), ("time", wintypes.DWORD),
        ("dwExtraInfo", ctypes.POINTER(wintypes.ULONG)),
    ]


# LRESULT is LONG_PTR; declaring it (and the argtypes) matters on 64-bit --
# without it ctypes truncates the LPARAM and CallNextHookEx raises inside
# the hook callback, which silently breaks the whole chain.
_HOOKPROC = ctypes.WINFUNCTYPE(
    wintypes.LPARAM, ctypes.c_int, wintypes.WPARAM, wintypes.LPARAM,
)
if _user32 is not None:  # pragma: no branch - trivial guard
    _user32.CallNextHookEx.argtypes = [
        wintypes.HHOOK, ctypes.c_int, wintypes.WPARAM, wintypes.LPARAM,
    ]
    _user32.CallNextHookEx.restype = wintypes.LPARAM
    _user32.SetWindowsHookExW.argtypes = [
        ctypes.c_int, _HOOKPROC, wintypes.HINSTANCE, wintypes.DWORD,
    ]
    _user32.SetWindowsHookExW.restype = wintypes.HHOOK


class InputWatcher:
    """Watch for input the *user* generates, ignoring Elaina's own.

    One instance is meant to be created for the process and shared. Start it
    once; it runs a daemon thread and stops with the app.
    """

    def __init__(self, *, clock=None) -> None:
        self._clock = clock or time.monotonic
        self._lock = threading.Lock()
        self._last_real_input: float | None = None
        self._real_mouse_events = 0
        self._real_key_events = 0
        self._injected_events = 0
        self._self_echo_events = 0
        self._last_self_input: float | None = None
        self._last_real_kind = ""
        self._thread: threading.Thread | None = None
        self._stop = threading.Event()
        self._installed = threading.Event()
        self._install_error = ""
        # Kept alive deliberately: Windows holds a raw pointer to these
        # trampolines, and letting them be collected crashes the hook chain.
        self._mouse_proc = None
        self._key_proc = None

    # ------------------------------------------------------------------
    # lifecycle

    def start(self) -> bool:
        """Install the hooks. Returns whether watching is actually active."""
        if _user32 is None:
            self._install_error = "Windows input hooks are not available here."
            return False
        if self._thread is not None and self._thread.is_alive():
            return self._installed.is_set()
        self._stop.clear()
        self._installed.clear()
        self._thread = threading.Thread(
            target=self._pump, name="elaina-input-watcher", daemon=True,
        )
        self._thread.start()
        self._installed.wait(_HOOK_INSTALL_TIMEOUT_SECONDS)
        return self._installed.is_set()

    def stop(self) -> None:
        self._stop.set()
        thread = self._thread
        if thread is not None:
            thread.join(timeout=1.0)
        self._thread = None

    @property
    def available(self) -> bool:
        """True when real input is genuinely being observed."""
        return self._installed.is_set()

    @property
    def unavailable_reason(self) -> str:
        return self._install_error

    # ------------------------------------------------------------------
    # hook plumbing

    def _pump(self) -> None:
        mouse_hook = key_hook = None
        try:
            self._mouse_proc = _HOOKPROC(self._on_mouse)
            self._key_proc = _HOOKPROC(self._on_key)
            mouse_hook = _user32.SetWindowsHookExW(
                _WH_MOUSE_LL, self._mouse_proc, None, 0,
            )
            key_hook = _user32.SetWindowsHookExW(
                _WH_KEYBOARD_LL, self._key_proc, None, 0,
            )
            if not mouse_hook or not key_hook:
                self._install_error = (
                    "Windows refused to install the input hooks, so I cannot "
                    "reliably tell your input apart from mine."
                )
                return
            self._installed.set()
            message = wintypes.MSG()
            while not self._stop.is_set():
                while _user32.PeekMessageW(
                    ctypes.byref(message), None, 0, 0, 1,
                ):
                    _user32.TranslateMessage(ctypes.byref(message))
                    _user32.DispatchMessageW(ctypes.byref(message))
                time.sleep(_PUMP_INTERVAL_SECONDS)
        except Exception as error:  # pragma: no cover - platform failure
            self._install_error = (
                f"Input watching failed to start ({type(error).__name__})."
            )
        finally:
            self._installed.clear()
            for hook in (mouse_hook, key_hook):
                if hook:
                    try:
                        _user32.UnhookWindowsHookEx(hook)
                    except Exception:
                        pass

    def note_self_input(self) -> None:
        """Elaina is about to inject something. Remember when.

        The injected flag is the primary test and it is the right one --
        measured, 26 mouse and 6 keyboard events from CursorDriver all
        arrived flagged. But "measured on one machine" is not "true on
        every machine": a pointing-device driver, an overlay, or a remote
        session can pass one of our own events through unflagged, and the
        cost of believing it is that Elaina cancels her own work and
        blames the person for it.

        So an unflagged event arriving in the moment after we injected one
        is treated as ours. It costs a fraction of a second of
        responsiveness to a real interruption, which is the cheaper of the
        two mistakes by a wide margin.
        """
        with self._lock:
            self._last_self_input = self._clock()

    def _record_real(self, *, mouse: bool) -> None:
        now = self._clock()
        with self._lock:
            recent_self = (
                self._last_self_input is not None
                and now - self._last_self_input < SELF_ECHO_SECONDS
            )
            if recent_self:
                self._self_echo_events += 1
                return
            self._last_real_input = now
            self._last_real_kind = "mouse" if mouse else "key"
            if mouse:
                self._real_mouse_events += 1
            else:
                self._real_key_events += 1

    def _on_mouse(self, code, wparam, lparam):
        # Deliberately minimal: this runs for every mouse event on the
        # machine, ahead of the application that will receive it.
        if code >= 0:
            try:
                data = ctypes.cast(
                    lparam, ctypes.POINTER(_MSLLHOOKSTRUCT),
                ).contents
                if data.flags & _LLMHF_INJECTED:
                    self._injected_events += 1
                else:
                    self._record_real(mouse=True)
            except Exception:
                pass
        return _user32.CallNextHookEx(None, code, wparam, lparam)

    def _on_key(self, code, wparam, lparam):
        if code >= 0:
            try:
                data = ctypes.cast(
                    lparam, ctypes.POINTER(_KBDLLHOOKSTRUCT),
                ).contents
                if data.flags & _LLKHF_INJECTED:
                    self._injected_events += 1
                else:
                    self._record_real(mouse=False)
            except Exception:
                pass
        return _user32.CallNextHookEx(None, code, wparam, lparam)

    # ------------------------------------------------------------------
    # queries

    def seconds_since_user_input(self) -> float | None:
        """How long since the person last touched the machine.

        ``None`` means "no real input has been seen" -- which is also what a
        watcher that never installed reports, so callers must check
        :attr:`available` rather than reading None as "the user is idle".
        """
        with self._lock:
            last = self._last_real_input
        if last is None:
            return None
        return max(0.0, self._clock() - last)

    def user_active_within(self, seconds: float) -> bool:
        """True when the person used the machine in the last ``seconds``."""
        elapsed = self.seconds_since_user_input()
        if elapsed is None:
            return False
        return elapsed <= max(0.0, float(seconds))

    def mark(self) -> float:
        """A checkpoint value for :meth:`user_input_since`."""
        return self._clock()

    def user_input_since(self, marker: float) -> bool:
        """Whether the person has provided input since a checkpoint.

        This is the mid-run interruption test: take a mark before an action,
        ask afterwards. Unlike pointer-position comparison it also catches
        typing, which never moves the mouse at all.
        """
        with self._lock:
            last = self._last_real_input
        return last is not None and last > marker

    def counters(self) -> dict[str, int]:
        """Event tallies, for diagnostics and the live checks."""
        with self._lock:
            return {
                "real_mouse": self._real_mouse_events,
                "real_key": self._real_key_events,
                "injected": self._injected_events,
                "self_echo": self._self_echo_events,
            }

    def last_real_event(self) -> tuple[str, float | None]:
        """What the last unflagged event was, and when. For the log.

        A cancellation that says "you moved the mouse" has to be able to
        show the event it is talking about.
        """
        with self._lock:
            return self._last_real_kind, self._last_real_input
